# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go module update

on:
  push:
    paths:
      - 'go.mod'
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build
      run: go mod tidy

    - name: Update Submodules
      run: |
          git config --global user.email "avkiller2012@gmail.com"
          git config --global user.name "avkiller"
          
          if git status --porcelain | grep -q .; then
            echo "代码发生变化推送最新更改"
            # 执行推送操作
            git add .
            git commit -m "Update go modules"
            git push
          else
            echo "代码没有发生变化"
          fi
          
